version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12.2
    pre_build:
        commands:
            - echo Nothing to do in the pre_build phase...
    build:
        commands:
            - echo Build started on `date`
            - yarn install
            - yarn build
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    baseDirectory: /dist
    files:
        - '**/*'
cache:
    paths:
        - node_modules/**/*
